<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* This file handles single entries, but only exists for the sake of child theme forward compatibility.
add_action( 'genesis_after_entry_content', 'social_share_btn' );
function social_share_btn() {
	echo '<div class="social-media-icons">
            <div class="facebook-button">
                <div class="fb-like" data-href="<?php the_permalink(); ?>" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
            </div>    
            <div class="gplus-button">
                <div class="g-plusone" data-href="<?php the_permalink(); ?>" data-size="medium"></div>
            </div>
          </div><!-- .social-media-icons -->';
}
genesis();
